language: ruby
rvm:
- 2.2.2
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAJRG6MBP2YO7UWGCA
  secret_access_key:
    secure: p37/iSAaYGqV3pPyeEdo/XEtb81DH8HspuZJ5Tt0LrhbN8TCLh6jTKnYkgQrKZDzCAQAxWfkN+Ry0xW6/f1ic4C4rQG6lsnQ34t2OmzusP7Uf9nZlnwHphyPE5l4aTu3w//aKHq7OLGmEaF2tJLKVSpHUMqny/9JuRmw1nhfA7gXd1StcS9/+ZVndJ85GtXjVcveVPMSv5SZlJXSi90onho3ZF1YdsnC8CvFmbLsIfsoiysBo0WCnSYMyBJzbG8GBguGqO5TVC/kKryhoC62HcgyDauct4C0Sc0IoovV/JgISpEDzDd/pBin9L1jw2EPsjFQ30B0GoNXnyYX4LwjCrnQl1ptj7IImbSyoPFmjWfdiXYbu49s2xU7ygS+pHHbCjttnqsjEEfM7bqNfChQNb7YByQpf/pu8xuztlOMhHKlW8jAl/64Yc/LD7wZZ7pSFac3Hs3nODTrO528iPd6jJ+36uN28H1lIrs5PzEDOuy9nEyrSIMNk3OWwOYSAqX7xci39jJqTb5xjIcj7g+QGI/I+1xQyJr5aNrOefYqVonKECDkPdUouYlaL3zCx8FTcEYFbZK1C2UZa1Mo3qzCPGJ40SpdjQQDMuF5Xv0Sr3sOb8NopYuPpNWeVGSPAnshsSCEp4H437wMR9s+K88sUhwJ3XZx0fmSIcfKO/HiSzI=
  bucket: aktrail.org
  region: us-west-2
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    repo: javbotero/Trans-Alaska-Trail
notifications:
  email:
    recipients:
    - javier.botero@gmail.com
    on_success: always
    on_failure: always
